name: Test Action

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: Run Action Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['18', '20']
        install_cdk: ['true', 'false']
        cdk_version: ['latest', '2.1020']
        report_outdated_packages: ['true', 'false']
        python_version: ['', '3.10']

    steps:
      - uses: actions/checkout@v5

      - name: Run Action
        uses: ./
        with:
          project_root: .github/test_project
          node_version: ${{ matrix.node_version }}
          install_cdk: ${{ matrix.install_cdk }}
          cdk_version: ${{ matrix.cdk_version }}
          python_version: ${{ matrix.python_version }}
          report_outdated_packages: ${{ matrix.report_outdated_packages }}

      - name: Test uv installed
        run: uv --version

      - name: Test Python version
        if: matrix.python_version != ''
        run: uv run python --version | grep ${{ matrix.python_version }}

      - name: Test cdk installed
        if: matrix.install_cdk == 'true'
        run: |
          node --version
          cdk --version
