name: Test Action

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: Run Action Tests
    runs-on: runs-on
    strategy:
      matrix:
        node_version: ['18', '20']
        install_cdk: ['true', 'false']
        cdk_version: ['latest', '2.1027', '2.1020']
        report_outdated_packages: ['true', 'false']

    steps:
      - uses: actions/checkout@v4

      - name: Run Action
        uses: ./
        with:
          project_root: .github/test_project
          node_version: ${{ matrix.node_version }}
          install_cdk: ${{ matrix.install_cdk }}
          cdk_version: ${{ matrix.cdk_version }}
          report_outdated_packages: ${{ matrix.report_outdated_packages }}
